// js/tickers.js
const tickers = [
  // --- TradingView 銘柄 ---
  { id: "nas100", name: "NAS100(CFD)", symbol: "FOREXCOM:NAS100" },
  { id: "ni225", name: "日経先物", symbol: "OSE:NK2251!" },
  { id: "us500", name: "S%P500(CFD)", symbol: "US500" },
  { id: "dji", name: "NYダウ", symbol: "AMEX:DIA" },
  { id: "usdjpy", name: "USDJPY", symbol: "USDJPY" },
  { id: "nvda", name: "NVDA", symbol: "NASDAQ:NVDA" },
  { id: "aapl", name: "AAPL", symbol: "NASDAQ:AAPL" },
  { id: "tsla", name: "TSLA", symbol: "NASDAQ:TSLA" },
  { id: "msft", name: "MSFT", symbol: "NASDAQ:MSFT" },
  { id: "sony", name: "SONY", symbol: "NYSE:SONY" },
  { id: "btc", name: "BTC", symbol: "BINANCE:BTCUSDT" },
  { id: "vix", name: "VIX(Future)", symbol: "CAPITALCOM:VIX" },
  { id: "gold", name: "GOLD", symbol: "TVC:GOLD" },
  { id: "oil", name: "OIL", symbol: "TVC:USOIL" },
  { id: "ni225(cfd)", name: "NI225(CFD)", symbol: "FOREXCOM:JP225" },

  // --- スプレッドシート（独自）銘柄 ---
  // スプレッドシート銘柄：symbolにGoogleFinanceのコードを入れる
  // スプレッドシートの A列（名前）と name を一致させる
  {
    id: "sheet_nikkei225",
    name: "Nikkei 225",
    type: "sheet",
    symbol: "/indices/japan-ni225",
  },
  {
    id: "sheet_sp500",
    name: "S&P 500",
    type: "sheet",
    symbol: "/indices/us-spx-500",
  },
  {
    id: "sheet_dow30",
    name: "Dow 30",
    type: "sheet",
    symbol: "/indices/us-30",
  },
  {
    id: "sheet_nasdaq100",
    name: "Nasdaq 100",
    type: "sheet",
    symbol: "/indices/nq-100",
  },
  {
    id: "sheet_dax",
    name: "DAX",
    type: "sheet",
    symbol: "/indices/germany-30",
  },
  {
    id: "sheet_ftse100",
    name: "FTSE 100",
    type: "sheet",
    symbol: "/indices/uk-100",
  },
  {
    id: "sheet_shanghaicomp",
    name: "Shanghai Comp",
    type: "sheet",
    symbol: "/indices/shanghai-composite",
  },
  {
    id: "sheet_hangseng",
    name: "Hang Seng",
    type: "sheet",
    symbol: "/indices/hang-sen-40",
  },
  {
    id: "sheet_nikkei225futures",
    name: "Nikkei 225 Futures",
    type: "sheet",
    symbol: "/indices/japan-225-futures",
  },
  {
    id: "sheet_sp500futures",
    name: "S&P 500 Futures",
    type: "sheet",
    symbol: "/indices/us-spx-500-futures",
  },
  {
    id: "sheet_nasdaq100fut",
    name: "Nasdaq 100 Fut",
    type: "sheet",
    symbol: "/indices/nq-100-futures",
  },
  {
    id: "sheet_dowfutures",
    name: "Dow Futures",
    type: "sheet",
    symbol: "/indices/us-30-futures",
  },
  {
    id: "sheet_us30y",
    name: "U.S. 30Y",
    type: "sheet",
    symbol: "/rates-bonds/u.s.-30-year-bond-yield",
  },
  {
    id: "sheet_us10y",
    name: "U.S. 10Y",
    type: "sheet",
    symbol: "/rates-bonds/u.s.-10-year-bond-yield",
  },
  {
    id: "sheet_us5y",
    name: "U.S. 5Y",
    type: "sheet",
    symbol: "/rates-bonds/u.s.-5-year-bond-yield",
  },
  {
    id: "sheet_us2y",
    name: "U.S. 2Y",
    type: "sheet",
    symbol: "/rates-bonds/u.s.-2-year-bond-yield",
  },
  {
    id: "sheet_japan30y",
    name: "Japan 30Y",
    type: "sheet",
    symbol: "/rates-bonds/japan-30-year-bond-yield",
  },
  {
    id: "sheet_japan10y",
    name: "Japan 10Y",
    type: "sheet",
    symbol: "/rates-bonds/japan-10-year-bond-yield",
  },
  {
    id: "sheet_japan5y",
    name: "Japan 5Y",
    type: "sheet",
    symbol: "/rates-bonds/japan-5-year-bond-yield",
  },
  {
    id: "sheet_japan2y",
    name: "Japan 2Y",
    type: "sheet",
    symbol: "/rates-bonds/japan-2-year-bond-yield",
  },
  {
    id: "sheet_germany10y",
    name: "Germany 10Y",
    type: "sheet",
    symbol: "/rates-bonds/germany-10-year-bond-yield",
  },
  {
    id: "sheet_gold",
    name: "Gold",
    type: "sheet",
    symbol: "/commodities/gold",
  },
  {
    id: "sheet_wtioil",
    name: "WTI Oil",
    type: "sheet",
    symbol: "/commodities/crude-oil",
  },
  {
    id: "sheet_copper",
    name: "Copper",
    type: "sheet",
    symbol: "/commodities/copper",
  },
  {
    id: "sheet_sp500vix",
    name: "S&P 500 VIX",
    type: "sheet",
    symbol: "/indices/volatility-s-p-500",
  },
  {
    id: "sheet_phlxsemiconductor",
    name: "PHLX Semiconductor",
    type: "sheet",
    symbol: "/indices/phlx-semiconductor",
  },
];
